baseURL      = 'https://liphium.com/'
languageCode = 'en-us'
title        = 'Liphium'
[menu]
  # The main menu
  [[menu.main]]
    name   = "Chat"
    url    = "/chat/"
    weight = 1
  [[menu.main]]
    name   = "Services"
    url    = "/services/"
    weight = 2
  [[menu.main]]
    name   = "Documentation"
    url    = "/docs/"
    weight = 3
  [[menu.main]]
    name   = "Blog"
    url    = "/blog/"
    weight = 4
  # Menu for the footer
  [[menu.footer]]
    name   = "Home"
    url    = "/"
    weight = 1
  [[menu.footer]]
    name   = "Privacy & Terms"
    url    = "/legal/terms/"
    weight = 2
  [[menu.footer]]
    name   = "Impressum"
    url    = "/legal/impressum/"
    weight = 3
